### ISSUE TITLE
 Fatal error: Class 'rcube_addressbook' not found

### ISSUE THREAD

**Issue by Mokshes** [johndoh/roundcube-globaladdressbook#44]
Fatal error: Class 'rcube_addressbook' not found .....folder.....

**Comment by johndoh** [comment]
please provide more details. what is the full error? what version of the plugin are you running and what version of roundube?

**Comment by Mokshes** [comment]
i want to fetch the google contact and icloud contact using codeigniter

**Comment by johndoh** [comment]
what does that have to do with this plugin? I do not understand the issue.

**Comment by Mokshes** [comment]
I do not know from where to start the things.

**Comment by johndoh** [comment]
I'm closing this issue coz I'm not sure what this has to do with the globaladdressbook plugin.
