### ISSUE TITLE
The regular expression applies to all users

### ISSUE THREAD

**Issue by Artem2710** [johndoh/roundcube-globaladdressbook#47]
The regular expression applies to all users. All users can delete contacts, even those who do not have "admin @" in the name. How to fix it?
![2019-02-26_1031](https://user-images.githubusercontent.com/38757512/53398242-d0684600-39b1-11e9-89cf-cd1f45c990ee.png)

**Comment by johndoh** [comment]
this is fixed in version 1.11.1
