### ISSUE TITLE
Set global addressbook as default

### ISSUE THREAD

**Issue by drlight17** [johndoh/roundcube-globaladdressbook#49]
Hi. Is there any way to set created global address book as default in the list of contact groups?

**Comment by johndoh** [comment]
what exactly do you by "default"?

**Comment by drlight17** [comment]
I mean selected when user come to the page "Contacts". There are Personal and collected contact groups besides the Global. When user without admin priveleges tries to select default (selected) group,  there is no option to set Global address book. But when the admin user does this - Global option appears.

**Comment by johndoh** [comment]
Write access to the global address book is controlled by the config params `globaladdressbook_perms` and `globaladdressbook_admin`. You can choose if everyone has write access or only admins.

**Comment by drlight17** [comment]
Users must have read only permissions on global addressbook. But why they can't set global adressbook as default addressbook? There is no option to choose it. Only admin can set global adressbook as his default addressbook.

**Comment by johndoh** [comment]
Only writable address books can be defined as `default_addressbook`. I think this is because this setting is used for things like which address book a contact should be added to when you click on "Add to address book" when viewing an email.

**Comment by TBG-FR** [comment]
I'm late to the party, but I tried adding `$config['default_addressbook'] = 'global'` inside my roundcube configuration and it works, even for users with read-only permissions

Maybe that would be worth a line in the README ? 👀
