### ISSUE TITLE
GlobalAddressBook plugin not working anymore in 1.4.x versions?

### ISSUE THREAD

**Issue by informas** [johndoh/roundcube-globaladdressbook#51]
Hello,

Since I have been updating Roundcube with versions 1.4.x the GlobalAddressBook plugin does not work anymore.

I am using the latest version of the plugin, 1.11. And I have tested it with Roundcube versions 1.4.2 and 1.4.4.

Apparently, once the email is sent, the window to enter the data of the new contacts does not open (if applicable)

Is it due to a configuration problem? Any incompatibility with new versions of Roundcube?

I have tried it with both Larry and Elastic skins.

Any suggestion?

Thank you.

**Comment by johndoh** [comment]
> Apparently, once the email is sent, the window to enter the data of the new contacts does not open (if applicable)

There has never been any such functionality in this plugin. I am going to close this because I think you are talking about some other plugin. If I am wrong please reopen with more details.

**Comment by informas** [comment]
You're right!
I apologize, I got confused about the plugin.
Thanks.
Best regards.
