### ISSUE TITLE
Automatically populate the GAB

### ISSUE THREAD

**Issue by himuura** [johndoh/roundcube-globaladdressbook#57]
First of all, nice plugin mate!
Secondly, is there a way to populate the global address book (GAB) with the emails already created in roundcube? Cant seem to find a way to get the email accounts from the mail server.
Thanks in advance!

**Comment by johndoh** [comment]
if you have the email addresses in a CSV or vCard file you can use the contact import function in Roundcube to populate it but there is nothing "automatic" as it depends entirely on your backend setup.

**Comment by TBG-FR** [comment]
> First of all, nice plugin mate! Secondly, is there a way to populate the global address book (GAB) with the emails already created in roundcube? Cant seem to find a way to get the email accounts from the mail server. Thanks in advance!

Did you find a way to do this ? I suppose you need to do a custom script that populate/update SQL data ?

**Comment by TBG-FR** [comment]
> > First of all, nice plugin mate! Secondly, is there a way to populate the global address book (GAB) with the emails already created in roundcube? Cant seem to find a way to get the email accounts from the mail server. Thanks in advance!
> 
> Did you find a way to do this ? I suppose you need to do a custom script that populate/update SQL data ?

I'm trying to make an authenticated cURL request that would do the same as a "manual" import, in order to pass data through Roundcube functions (to avoid reinventing the wheel and making SQL calls)

Here's what the logs look like in Roundcube for a manual import
```
POST /?_task=addressbook&_action=import HTTP/1.1" 200 2735 "http://localhost:9000/?_task=addressbook&_framed=1&_target=global&_action=import
```

No luck for now but I'll keep digging
