### ISSUE TITLE
Adding SQL in the config file

### ISSUE THREAD

**Issue by vinaypri** [johndoh/roundcube-globaladdressbook#58]
I want to connect our SQL backend which has email addresses to the addressbook, such that search by domain is possible. However I do not find any place in the config file of global_addressbook to add the SQL. Please suggest where this is to be done.
Sorry to be sending as an issue but i could not find any other place to pose this question.

**Comment by johndoh** [comment]
The plugin uses the SQL connection defined in the core, storing entries in the `contacts` table.
