### ISSUE TITLE
I need two or more addressbook of global with diffrent name?how can i do ? 

### ISSUE THREAD

**Issue by wjcroom** [johndoh/roundcube-globaladdressbook#59]
first I try to let group contain some others groups . I failed .
so  if add some other globaladdressbooks. with names. ep.  onebook,two book, work book, friend book.
how can i do this?.

**Comment by johndoh** [comment]
The config allows for multiple address books because it uses an array format. e.g.
```php
$config['globaladdressbooks'] = [
    'global1' => [
        'name' => 'Shared Contacts 1',
        'user' => '_global_addressbook_user1_',
        ...
    ],
    'global2' => [
        'name' => 'Shared Contacts 2',
        'user' => '_global_addressbook_user2_',
        ...
    ]
];
```
The options provided in the config file exist on a per book basis the import thing is the `user` config is different for each address book.

You have to version 2 of the plugin for this multi-config setup to work.

**Comment by wjcroom** [comment]
oh. thinks ,

**Comment by wjcroom** [comment]
if i con get books for carddav servers , that will be good

**Comment by johndoh** [comment]
carddav is out of scope for this plugin
